FROM docker.coneda.net:443/ubuntu:latest

MAINTAINER Moritz Schepp <moritz.schepp@gmail.com>

VOLUME /opt/kor/shared
VOLUME /etc/ssmtp
EXPOSE 8000

ENV RAILS_ENV test

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y build-essential libxml2-dev libxslt-dev git-core curl libssl-dev && \
    apt-get install -y libmysqlclient-dev imagemagick libav-tools zip libreadline6-dev ssmtp file && \
    apt-get clean && \
    git clone https://github.com/sstephenson/rbenv.git /opt/rbenv && \
    git clone https://github.com/sstephenson/ruby-build.git /opt/rbenv/plugins/ruby-build && \
    echo 'export RBENV_ROOT=/opt/rbenv' >> /etc/profile.d/rbenv.sh && \
    echo 'export PATH=/opt/rbenv/bin:/opt/rbenv/shims:$PATH' >> /etc/profile.d/rbenv.sh && \
    echo 'eval "$(rbenv init -)"' >> /etc/profile.d/rbenv.sh \
    echo '. /etc/profile.d/rbenv.sh' >> /etc/bash.bashrc \
    echo 'gem: --no-ri --no-rdoc' >> /etc/gemrc && \
    useradd -m kor

ENV RBENV_ROOT /opt/rbenv
ENV PATH /opt/rbenv/bin:/opt/rbenv/shims:$PATH

RUN mkdir -p /opt/kor/shared/data

ADD ruby-version /opt/kor/ruby-version

RUN rbenv install `cat /opt/kor/ruby-version` && \
    rbenv global `cat /opt/kor/ruby-version` && \
    rbenv shims && \
    gem install bundler

RUN cd /opt && \
    apt-get install -y wget && \
    wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2 && \
    tar xjf phantomjs-1.9.8-linux-x86_64.tar.bz2 && \
    ln -sfn /opt/phantomjs-1.9.8-linux-x86_64/bin/phantomjs /usr/bin/phantomjs && \
    rm phantomjs-1.9.8-linux-x86_64.tar.bz2

ENV HEADLESS true

ADD kor.tar /opt/kor/current
WORKDIR /opt/kor/current

RUN bash -c "bundle install --path /opt/kor/bundle --without development production" kor && \
    ln -sfn /opt/kor/shared/database.yml /opt/kor/current/config/database.yml && \
    ln -sfn /opt/kor/shared/kor.yml /opt/kor/current/config/kor.yml && \
    ln -sfn /opt/kor/shared/kor.app.yml /opt/kor/current/config/kor.app.yml && \
    ln -sfn /opt/kor/shared/legal.txt /opt/kor/current/config/legal.txt && \
    ln -sfn /opt/kor/shared/contact.txt /opt/kor/current/config/contact.txt && \
    ln -sfn /opt/kor/shared/data /opt/kor/current/data && \
    ln -sfn /opt/kor/shared/log /opt/kor/current/log
